Fix CI failure on Ruby 4.0
The version of `rake` in `Gemfile.lock` is old, and running tests on Ruby 4.0 causes the following error. To fix this, update gems with `bundle update`.

```
/Users/willnet/.local/share/mise/installs/ruby/4.0.3/lib/ruby/gems/4.0.0/gems/rake-13.0.6/lib/rake.rb:33:in 'Kernel#require': cannot load such file -- ostruct (LoadError)
```

At first, try updating only `rake`, but then `rubocop` fails with the following error, so update all gems instead.

```
LoadError: cannot load such file -- racc/parser (LoadError)
/Users/willnet/.local/share/mise/installs/ruby/4.0.3/bin/bundle:25:in '<main>'
Tasks: TOP => default => rubocop
```

However, running `bundle update` on Ruby 4.0 installs `parallel 2.1.0`, which depends on Ruby >= 3.3.0, so `bundle install` fails on Ruby versions older than 3.3.

Because of these issues, decide that removing `Gemfile.lock` is the most stable way to keep CI working, and delete `Gemfile.lock`.